//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscal
    {
        public Fiscal()
        {
            this.Plano = new HashSet<Plano>();
            this.Plano1 = new HashSet<Plano>();
        }
    
        public int id_fisc { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<Plano> Plano { get; set; }
        public virtual ICollection<Plano> Plano1 { get; set; }
    }
}
