//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LI4Entities : DbContext
    {
        public LI4Entities()
            : base("name=LI4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Estabelecimento> Estabelecimento { get; set; }
        public DbSet<Fiscal> Fiscal { get; set; }
        public DbSet<Foto> Foto { get; set; }
        public DbSet<Nota> Nota { get; set; }
        public DbSet<Plano> Plano { get; set; }
        public DbSet<Questao> Questao { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Visita> Visita { get; set; }
        public DbSet<VisitaQuestao> VisitaQuestao { get; set; }
        public DbSet<Voz> Voz { get; set; }
    }
}
