//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        public Questao()
        {
            this.VisitaQuestao = new HashSet<VisitaQuestao>();
        }
    
        public int id_quest { get; set; }
        public string pergunta { get; set; }
    
        public virtual ICollection<VisitaQuestao> VisitaQuestao { get; set; }
    }
}
