//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaQuestao
    {
        public int Questao { get; set; }
        public int Visita { get; set; }
        public string Resposta { get; set; }
    
        public virtual Questao Questao1 { get; set; }
        public virtual Visita Visita1 { get; set; }
    }
}
